apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jamie-net-app
  name: jamie-net-app
spec: 
  selector:
    app: jamie-net-app
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 80
  type: LoadBalancer